      - name: Set up Android SDK
        uses: android-actions/setup-android@v3
        with:
          packages: |
            platform-tools
            platforms;android-36
            build-tools;36.0.0
          accept-android-sdk-licenses: true
